kontakt: Tu ma môžete kontaktovať
title: Patrik Januška
email: januska.patrik@gmail.com
description: >
   Fakulta informatiky a informačných technológií STU v Bratislave
baseurl: ""
url: "http://patro213.github.io/webove_publikovanie/zadanie_1"
github_username:  patro213
facebook_username:  Patrik Januška
fb_username: patrik.januska
fiit: Fakulta informatiky a informačných technológií STU v Bratislave

markdown: kramdown
